# Configuration file for Caddis API Automation
# Environment variables will override these values

# Caddis API Configuration
caddis_api_url: "https://api.caddis.com.ar"  # URL base de la API
# Las credenciales NO se guardan acá. Se leen de las variables de entorno:
#   CADDIS_USERNAME y CADDIS_PASSWORD

# Google Sheets Configuration
# Este valor se sobreescribe con la env var GOOGLE_SHEETS_ID
google_sheets_id: ""

# Price Lists to Extract (IDs)
price_lists:
  - 1   # Minorista Ars
  - 2   # Dealer Ars
  - 3   # Dealer 1 Ars
  - 5   # Dealer 30d Ars
  - 7   # Nautica Dealer Usd
  - 8   # Dealer 60d Ars
  - 9   # Mino Ml Premium Ars
  - 12  # Sub Distribuidor Usd
  - 14  # Dealer 55mkup Ars
  - 19  # Dealer 50mkup Ars
  - 20  # Anterior Mino Ars
  - 21  # Mixta Ars
  - 22  # Grouping 70mkup Ars
  - 23  # Dealer Cencosud Ars
  - 24  # Nautica Dealer 1 Usd
  - 25  # Nautica Dealer Ars
  - 26  # Nautica Dealer 1 Ars
  - 27  # Fob Standard Usd
  - 28  # Dealer Golf Ars
  - 29  # Gpsmundo Srl
  - 30  # Dealer Meli Ars
  - 31  # Dealer 5g Ars
  - 32  # Fob Supplier Llc
  - 33  # Dealer Diggit Ars

# Rate limiting and retry configuration
rate_limit_delay: 1.0   # seconds between API calls (antes 0.1)
request_timeout: 60     # seconds
max_retries: 5          # reintentos por página/lista